---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.3
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "debian-9"
          - "debian-10"
          - "ubuntu-2004"
          - "ubuntu-2104"
          - "amazonlinux-2"
          - "centos-7"
          - "centos-8"
          - "centos-stream-8"
          - "fedora-latest"
        suite:
          - "package"
          - "source-18"
          - "source-20"
          - "source-22"
          - "source-default"
          - "source-openssl"
        exclude:
          - os: "amazonlinux-2"
            suite: "source-openssl"
          - os: "fedora-latest"
            suite: "source-18"
          - os: "fedora-latest"
            suite: "source-openssl"
          - os: "ubuntu-2104"
            suite: "source-18"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Dokken
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  lua_test:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "centos-7"
        suite:
          - "source-lua"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Dokken
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  configtest:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "centos-7"
          - "centos-stream-8"
        suite:
          - "config-1"
          - "config-1-userlist"
          - "config-2"
          - "config-3"
          - "config-4"
          - "config-backend-search"
          - "config-acl"
          - "config-resolver"
          - "config-ssl-redirect"
          - "config-custom-template"
          - "config-custom-template"
          - "config-array"
          - "config-fastcgi"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Dokken
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
