---
name: Prevent file change

"on":
  pull_request_target:
    branches: [main]

jobs:
  prevent-metadata-change:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Prevent metadata.rb file change
        uses: xalvarez/prevent-file-change-action@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: metadata.rb
          trustedAuthors: &maintainers bmhughes,damacus,kitchen-porter,MarkGibbons,ramereth,Stromweld,xorima

  prevent-workflow-change:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Prevent workflow file change
        uses: xalvarez/prevent-file-change-action@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: .github/workflows
          trustedAuthors: *maintainers
          closePR: true
          allowNewFiles: false
